---@class FToolMenuEntry
---@field public Name string
---@field public Owner FToolMenuOwner
---@field public Type EMultiBlockType
---@field public UserInterfaceActionType EUserInterfaceActionType
---@field public TutorialHighlightName string
---@field public InsertPosition FToolMenuInsert
---@field public bShouldCloseWindowAfterMenuSelection boolean
---@field public ScriptObject UToolMenuEntryScript
---@field public StyleNameOverride string
---@field private bCommandIsKeybindOnly boolean
local FToolMenuEntry = {}
