---@class USetCollisionGeometryToolProperties : UInteractiveToolPropertySet
---@field public GeometryType ECollisionGeometryType
---@field public bAppendToExisting boolean
---@field public bUseWorldSpace boolean
---@field public InputMode ESetCollisionGeometryInputMode
---@field public bRemoveContained boolean
---@field public bEnableMaxCount boolean
---@field public MaxCount integer
---@field public MinThickness number
---@field public bDetectBoxes boolean
---@field public bDetectSpheres boolean
---@field public bDetectCapsules boolean
---@field public bSimplifyHulls boolean
---@field public HullTargetFaceCount integer
---@field public MaxHullsPerMesh integer @How many convex hulls can be used to approximate each mesh
---@field public ConvexDecompositionSearchFactor number @How much to search the space of possible decompositions beyond MaxHullsPerMesh; for larger values, will do additional work to try to better approximate mesh features (but resulting hulls may overlap more)
---@field public AddHullsErrorTolerance number @Error tolerance for adding more convex hulls, in cm.  For volumetric errors, the value will be cubed (so a value of 10 indicates a 10x10x10 volume worth of error is acceptable).
---@field public MinPartThickness number @Minimum part thickness for convex decomposition (in cm); hulls thinner than this will be merged into adjacent hulls, if possible.
---@field public bSimplifyPolygons boolean
---@field public HullTolerance number
---@field public SweepAxis EProjectedHullAxis
---@field public LevelSetResolution integer @Level set grid resolution along longest grid axis
---@field public SetCollisionType ECollisionGeometryMode
---@field public bUsingMultipleInputs boolean @Set by the tool to tell the settings object whether the tool is using multiple inputs.
local USetCollisionGeometryToolProperties = {}

